# Generated by Django 5.2.7 on 2025-10-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoIntegrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(db_index=True)),
                ('titulo', models.CharField(db_index=True, max_length=255)),
                ('autores', models.CharField(blank=True, max_length=255)),
                ('programa', models.CharField(blank=True, max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('palabras_clave', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('en_proceso', 'En proceso'), ('archivado', 'Archivado')], db_index=True, default='aprobado', max_length=30)),
                ('enlace', models.URLField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='proyectos/')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-anio', 'titulo'],
                'indexes': [models.Index(fields=['anio', 'estado'], name='catalogo_pr_anio_092343_idx')],
            },
        ),
    ]
