# Generated by Django 5.2.7 on 2025-10-16 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('seccion', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('anio', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProyectoIntegrador',
        ),
        migrations.AddField(
            model_name='alumno',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='catalogo.proyecto'),
        ),
    ]
